### ISSUE TITLE
context.options.headers.get is not a function

### ISSUE THREAD

**Issue by dongnaebi** [unjs/ofetch#521]
### Environment

all environment

### Reproduction

```ts
export const $ofetch = ofetch.create({
  timeout: 15000,
  onRequest({ options }) {
    options.headers = {
      ...options.headers,
      Authorization: token.value,
      UUID: uuid.value
    } as any
  },
})
```

### Describe the bug

```
context.options.headers.get is not a function
```

I started getting this error after upgrading to version 1.5.0 — everything worked fine in 1.4.1 and earlier versions.

### Logs

```sh

```

**Comment by kricsleo** [comment]
Can't reproduce. Could you provide a minimal reproduction using https://stackblitz.com/?

**Comment by Umid-Berdiev** [comment]
got TypeError: u.options.headers.get is not a function in NuxtJS app

**Comment by kricsleo** [comment]
> Can't reproduce in `v1.5.0`. Could you provide a minimal reproduction with [this example](https://stackblitz.com/~/github.com/kricsleo/starter-ts-minimal?file=index.mjs&startScript=dev)? 🙏

Thanks for all the reports, but could anyone provide a reproduction? 🙏

**Comment by yaowangmx** [comment]
> nuxt@3.18.1 too

Solution: Use `new Headers` to set the request headers in `onRequest`.
For example:
```
onRequest({ options }) {
  if (process.env.NODE_ENV === "production") {
    if (process.client) {
      options.baseURL = config.public.baseURL
    } else {
      options.baseURL = config.public.baseIntrantURL
    }
  }
  const hdrs = new Headers(options.headers || {})
  
  hdrs.set("X-Platform", "web")

  if (!process.client) {
    const reqHeaders = useRequestHeaders(["cookie"]) || {}
    if (reqHeaders.cookie) {
      hdrs.set("cookie", reqHeaders.cookie)
    }
    const { locale } = useI18n()
    if (locale?.value) {
      hdrs.set("locale", locale.value)
    }
  }

  options.headers = hdrs
}
```
